apiVersion: v1
kind: ConfigMap
metadata:
  name: image-resizer-config
  labels:
    app: image-resizer
data:
  BASE_URL: "https://image-resizer-taylinn-dev.apps.rm1.0a51.p1.openshiftapps.com"
  STORAGE_ENDPOINT: "http://minio:9000"
  STORAGE_BUCKET: "image-resizer"
  REDIS_URL: "redis://redis:6379/0"
