apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-resizer.fullname" . }}-secret
  labels:
    {{- include "image-resizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "image-resizer.databaseUrl" . | quote }}
  STORAGE_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  STORAGE_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
