apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-resizer.fullname" . }}-worker
  labels:
    {{- include "image-resizer.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-resizer.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "image-resizer.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args: ["-A", "app.tasks:celery_app", "worker", "--loglevel=info", "--concurrency={{ .Values.worker.concurrency }}"]
          envFrom:
            - configMapRef:
                name: {{ include "image-resizer.fullname" . }}-config
            - secretRef:
                name: {{ include "image-resizer.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
